AWSTemplateFormatVersion: "2010-09-09"

Description: "base datos RDS"

Parameters:
  Passwd:
    Description: password de la base datos
    Type: 'String'
    NoEcho: true
    Default: "12345678"
  
  TipoInstancia:
    Description: tipo de ec2
    Type: String
    Default: db.t2.micro

Resources:

  myBD: 
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      BackupRetentionPeriod: 0
      CopyTagsToSnapshot: false
      DBInstanceClass: !Ref TipoInstancia
      DBName: encuestabd
      DBSubnetGroupName: !Ref mySubnetConf
      DeletionProtection: false
      Engine: MySQL
      EngineVersion: "5.7.21"
      MasterUsername: "root"
      MasterUserPassword: !Ref Passwd
      MultiAZ: false
      Port: "3306"
      StorageType: gp2
      VPCSecurityGroups:
        - !ImportValue infraestructura-sgMysqlRDS

  mySubnetConf:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: 'redes privadas'
      DBSubnetGroupName: 'dbprivate'
      SubnetIds:
        - !ImportValue infraestructura-subnetPrivada1
        - !ImportValue infraestructura-subnetPrivada2

Outputs:
  myBDEndpoint:
    Description: endpoint bd
    Value: 
      !GetAtt myBD.Endpoint.Address
    Export:
      Name: basedatos-endpointRDS